version: '3'

tasks:
  # Сборка проекта
  build:
    desc: Build the application
    cmds:
      - go build -o bin/server.exe ./cmd/main.go

  # Запуск проекта
  run:
    desc: Run the application
    cmds:
      - go run ./cmd/main.go

  # Запуск всех тестов
  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  # Проверка покрытия тестами
  cover:
    desc: Check test coverage
    cmds:
      - go test -coverpkg=./... -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out

  # Открыть отчет о покрытии в браузере
  cover-html:
    desc: Show test coverage in browser
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out

  # Установка зависимостей (например, для тестов)
  tidy:
    desc: Clean and tidy go mod
    cmds:
      - go mod tidy
